### PR TITLE
Pin all dependency versions

### PR DESCRIPTION
**Pull request by charrondev**
I've pinned all of the dependency versions (after updating them to the latest semver minor which was actually what yarn resolved them to).

I've also added an npmrc so that all dependency versions are pinned in the future.

### CODE REVIEW

**Comment by DaazKu** [comment]
What is the reasoning behind this? Always being up to date on patch versions is generally a good idea.

**Comment by charrondev** [comment]
Because of stuff like this.

image

The default non-pinned version requested 4.6 and since this is javascript webpack has released 3 "minor" versions that things resolved too. So we come in on a monday I have to spend the first 2 hours of my day figuring out why webpack now parses JSON differently.

We can update version when we need to and we've tested them.

**Comment by cdepage** [comment]
@DaazKu Pinning to a specific version is a desirable behaviour because a large chunk of developers who create packages so not understand and/or properly follow the Semantic Versioning criteria. This results in packages that have patches or minor versions updated to AUTOMATICALLY UPDATE WITHOUT DEVELOPER VALIDATION and end up in production.

The change introduced in this PR will ensure that the code we build and test with is the code that is running in production and will not change magically.

**Comment by DaazKu** [comment]
> Pinning to a specific version is a desirable behaviour because a large chunk of developers who create packages so not understand and/or properly follow the Semantic Versioning criteria

Fair enough but not getting patches should be considered a mistake.

My point here is that by doing `~4.6.0` we would get the patches but not change minor version. 
If Webpack itself does not honour Semantic Versioning properly that's another thing.

That's what we do in our [compose.json](https://github.com/vanilla/vanilla/blob/master/composer.json) file:

**Pull request merged**
